- app/helpers/family_helper.rb
- app/operations/magi_medicaid/generate_and_publish_eligibility_documents.rb
- spec/operations/magi_medicaid/generate_and_publish_eligibility_documents_spec.rb
https://www.pivotaltracker.com/story/show/180116882
> add missing event key issues for OE notices

- app/operations/magi_medicaid/publish_document.rb
- spec/operations/magi_medicaid/publish_document_spec.rb
- spec/shared_examples/enrollments/family_response.rb
> honor communication preference when sending paper notices

- Gemfile.lock
[ME-180463686](https://www.pivotaltracker.com/story/show/180463686)
> update aca_entities gem

- app/helpers/financial_application_helper.rb
- app/operations/magi_medicaid/generate_and_publish_eligibility_documents.rb
- app/operations/magi_medicaid/publish_document.rb
- spec/operations/magi_medicaid/generate_and_publish_eligibility_documents_spec.rb
[180527756](https://www.pivotaltracker.com/story/show/180527756)
> fix error logging issues in polypress

- app/operations/reports/recon_pre_audit_processor.rb
- system/config/templates/features/enroll_app/reports.yml
https://www.pivotaltracker.com/n/projects/2502930/stories/180681123
> Fetch right key from RR

- .gitignore
- Gemfile
- Gemfile.lock
- Rakefile
- app/jobs/application_job.rb
- app/jobs/request_subscriber_coverage_history_job.rb
- app/operations/reports/fetch_and_store_subscribers_and_coverage_history.rb
- app/operations/reports/recon_pre_audit_processor.rb
- bin/sneakers_activejob
- config/application.rb
- config/initializers/sneakers.rb
- spec/jobs/request_subscriber_coverage_history_job_spec.rb
- spec/operations/reports/fetch_and_store_subscribers_and_coverage_history_spec.rb
> Activejob parallel

- Gemfile.lock
- Issue was caused due to code change in AcaEntites, had to update gem reference
> Fixes FRE notice issue

- Gemfile.lock
[ME-180776410](https://www.pivotaltracker.com/story/show/180776410)
> update aca entities gem reference

- Gemfile.lock
- app/helpers/financial_application_helper.rb
- app/operations/magi_medicaid/publish_document.rb
- spec/operations/magi_medicaid/publish_document_spec.rb
- spec/shared_examples/eligibilities/application_response.rb
[180463907](https://www.pivotaltracker.com/story/show/180463907)
> updates to honor communication preference for OE notice

- Gemfile
- Gemfile.lock
[IVL-180558616](https://www.pivotaltracker.com/story/show/180558616)
> update aca_entities and event_source gem reference

- Gemfile.lock
[ME-181014889](https://www.pivotaltracker.com/story/show/181014889)
> update aca_entities gem reference

- app/views/shared/header_ivl.html.erb
[ME-181158671](https://www.pivotaltracker.com/story/show/181158671)
> add extra space at the end of page number

- app/operations/magi_medicaid/publish_document.rb
- spec/operations/magi_medicaid/publish_document_spec.rb
[ME-181301515](https://www.pivotaltracker.com/story/show/181301515)
> update doc storage path

- app/operations/reports/generate_rcno_report.rb
> Ticket 181345929

- app/operations/reports/fetch_and_store_subscribers_and_coverage_history.rb
- app/operations/reports/generate_pre_audit_report.rb
- spec/operations/reports/generate_pre_audit_report_spec.rb
> Ticket 181357693

- app/operations/reports/generate_pre_audit_report.rb
- spec/operations/reports/generate_pre_audit_report_spec.rb
> Pre-Audit  Life Partner Relationship Fix & Transaction Code Type Fix

- app/jobs/request_subscriber_coverage_history_job.rb
- app/models/audit_report_datum.rb
- app/models/policy.rb
- app/operations/reports/fetch_and_store_subscribers_and_coverage_history.rb
- app/operations/reports/generate_rcno_report.rb
- app/operations/reports/request_coverage_history_for_subscriber.rb
- spec/operations/reports/generate_rcno_report_spec.rb
- spec/operations/reports/rcno_report_generation_processor_spec.rb
- spec/operations/reports/request_coverage_history_for_subsriber_spec.rb
> Populate missing audit data from rcni reports into rcno report

- app/operations/reports/generate_rcno_report.rb
- scripts/rcno_metric_report.rb
- spec/operations/reports/generate_rcno_report_spec.rb
> Parse out pipe symbols if we have data with pipes present

- app/operations/reports/generate_rcno_report.rb
- scripts/rcno_metric_report.rb
> Updates to RCNO report matching Criteria and RCNO metric report

- config/settings.yml
> Change settings from ME to DC

- config/settings.yml
> Revert "Change settings from ME to DC"

- app/operations/render_liquid.rb
- spec/operations/documents/create_spec.rb
- spec/shared_examples/eligibilities/application_response.rb
[ME-181888421](https://www.pivotaltracker.com/story/show/181888421)
> fix mailing address for eligibility and reminder notices

- app/controllers/application_controller.rb
- app/views/devise/shared/_links.html.erb
- app/views/layouts/_nav_links.html.erb
- config/routes.rb
[MAINT-182228379](https://www.pivotaltracker.com/n/projects/2481179/stories/182228379)
> hide sign up link

- app/views/new/templates/_template_row.html.erb
[MAINT-182236727](https://www.pivotaltracker.com/n/projects/2481179/stories/182236727)
> add target blank to pdf link

- Gemfile.lock
[ME-182202492](https://www.pivotaltracker.com/story/show/182202492)
> update aca entities gem version

- Gemfile.lock
[ME-IVL](https://www.pivotaltracker.com/story/show/182202492)
> update aca entities

- app/operations/magi_medicaid/publish_document.rb
- spec/operations/magi_medicaid/publish_document_spec.rb
[RM-98656](https://redmine.dchbx.org/issues/98656)
> pass primary person hbx_id instead of family_hbx_id to upload document

- app/operations/reports/generate_pre_audit_report.rb
[ME-182367090](https://www.pivotaltracker.com/n/projects/2502930/stories/182367090)
> fixing transaction code type on Cancelled Dependents for pre audits

- app/operations/reports/generate_rcno_report.rb
[ME-181994158](https://www.pivotaltracker.com/n/projects/2502930/stories/181994158)
> RCNO report generation fixes

- app/operations/reports/generate_rcno_report.rb
- scripts/rcno_metric_report.rb
> Do not compare aptc for canceled policies

- app/helpers/family_helper.rb
[ME-183700840](https://www.pivotaltracker.com/story/show/183700840)
> update family payload to include timestamp for preview

- Gemfile.lock
> update aca entities ref

- Gemfile.lock
[Pivotal-184264494](https://www.pivotaltracker.com/n/projects/2481183/stories/184264494)
> gemfile update for aca_entities

- Gemfile.lock
- app/event_source/subscribers/families/notices/tax_forms/tax1095a_notice_generation_subscriber.rb
- app/operations/documents/append_1095a_documents.rb
- spec/operations/magi_medicaid/publish_document_spec.rb
> update payload attribute in subscriber

- app/operations/documents/append_1095a_documents.rb
> updates tax document path

- app/models/irs_yearly_pdf_report.rb
- spec/shared_examples/enrollments/family_response.rb
> use plan_year attr instead of start_on

- app/helpers/family_helper.rb
> remove encrypted ssns from dummy payload

- app/operations/documents/append_1095a_documents.rb
- spec/shared_examples/enrollments/family_response.rb
> fixes MTTH cases and missing tax filer scenario

- app/models/irs_yearly_pdf_report.rb
> remove hard coded void value in pdf report

- app/helpers/family_helper.rb
- app/models/irs_yearly_pdf_report.rb
- spec/shared_examples/enrollments/family_response.rb
[ME-184285310](https://www.pivotaltracker.com/story/show/184285310)
> fixes issuer name display issue in 1095A form

- app/models/irs_yearly_pdf_report.rb
[IVL-184284178](https://www.pivotaltracker.com/n/projects/2481183/stories/184284178)
> fetch policy dates from insurance_policy

- Gemfile.lock
- app/event_source/subscribers/families/notices/tax_forms/tax1095a_notice_generation_subscriber.rb
- app/helpers/family_helper.rb
- app/models/irs_yearly_pdf_report.rb
- app/operations/documents/append_1095a_documents.rb
- app/operations/documents/create_with_insert.rb
- app/operations/magi_medicaid/publish_document.rb
- spec/operations/magi_medicaid/publish_document_spec.rb
- spec/shared_examples/enrollments/family_response.rb
[ME-184385613](https://www.pivotaltracker.com/story/show/184385613)
> refactor tax notices subscriber to listen events from fdsh gateway

- app/helpers/financial_application_helper.rb
[ME-184385613](https://www.pivotaltracker.com/story/show/184385613)
> avoid method overrides in financial application helper which was causing preview errors

- app/event_source/subscribers/families/notices/tax_forms/tax1095a_notice_generation_subscriber.rb
[ME-184385613](https://www.pivotaltracker.com/story/show/184385613)
> update incoming payload structure in subscriber

- app/operations/magi_medicaid/publish_document.rb
- spec/operations/magi_medicaid/publish_document_spec.rb
[ME-184615746](https://www.pivotaltracker.com/story/show/184615746)
> update paper notices folder for tax notices

- app/operations/reports/generate_pre_audit_report.rb
[ME-184640679](https://www.pivotaltracker.com/n/projects/2481183/stories/184640679)
> adding a logger file for the errors

- app/models/irs_yearly_pdf_report.rb
[ME-184849798](https://www.pivotaltracker.com/n/projects/2502930/stories/184849798#)
> fill empty values in spouse section if recipient is spouse

- Gemfile.lock
> update aca_entities sha to latest

- Gemfile.lock
[185768811](https://www.pivotaltracker.com/n/projects/2659995/stories/185768811)
> update aca_entities sha ref to latest

- app/helpers/financial_application_helper.rb
[185768811](https://www.pivotaltracker.com/n/projects/2659995/stories/185768811)
> add member determinations for eligible members

- Gemfile.lock
[185843838](https://www.pivotaltracker.com/n/projects/2659995/stories/185843838)
> update aca_entities sha ref

- app/event_source/subscribers/families/notices/faa_totally_ineligible/faa_totally_ineligible_notice_subscriber.rb
[185843838](https://www.pivotaltracker.com/n/projects/2659995/stories/185843838)
> register subscriber for total ineligibility notice

- app/helpers/financial_application_helper.rb
[185768811](https://www.pivotaltracker.com/n/projects/2659995/stories/185768811)
> refactor faa preview data and helper

- scripts/code_event_mappings_report.rb
[IVL Product Development - 186206349](https://www.pivotaltracker.com/story/show/186206349)
> adds validation script for verifying code and event mapping

- app/models/irs_yearly_pdf_report.rb
- spec/models/irs_yearly_pdf_report_spec.rb
- spec/shared_examples/enrollments/family_response.rb
https://www.pivotaltracker.com/story/show/186558977
> includes spouse as the recipient if filing jointly but not enrolled

- app/models/irs_yearly_pdf_report.rb
- spec/models/irs_yearly_pdf_report_spec.rb
- spec/shared_examples/enrollments/family_response.rb
- system/config/templates/features/enroll_app/reports.yml
- system/config/templates/features/tax_notices.yml
https://www.pivotaltracker.com/story/show/186528262
> rename issuer name on 1095A forms as approved by ME

- Gemfile.lock
Update the aca entities ref to include recent contract changes in support of [FRE notices](https://www.pivotaltracker.com/story/show/186314492).
https://www.pivotaltracker.com/story/show/186497126
https://www.pivotaltracker.com/story/show/186497137
> update aca ref

- app/models/irs_yearly_pdf_report.rb
- spec/models/irs_yearly_pdf_report_spec.rb
- spec/shared_examples/enrollments/family_response.rb
https://www.pivotaltracker.com/story/show/186558977
> display both spouses on tax form when filing jointly

- app/event_source/subscribers/families/notices/tax_forms/cap1095a_notice_generation_subscriber.rb
**Ref Ticket:** [pivotal_186373699](https://www.pivotaltracker.com/story/show/186373699)
**Current Branch Status:**
> add subscriber to consume cap 1095a payloads

- Gemfile.lock
[Jolly Podgers Development - 187062137](https://www.pivotaltracker.com/story/show/187062137)
* Updates Aca Entities gem sha to the latest.
> updates aca_entities sha

- app/controllers/new/templates_controller.rb
- app/entities/templates/template.rb
- app/models/bodies/body_model.rb
- app/models/templates/template_model.rb
- spec/entities/templates/template_spec.rb
- spec/models/bodies/body_model_spec.rb
- spec/operations/documents/create_spec.rb
Ticket reference: [187038979](https://www.pivotaltracker.com/story/show/187038979)
> sanitize params and validate for template

- app/models/templates/template_model.rb
https://www.pivotaltracker.com/n/projects/2640060/stories/187038979
> remove element from list of blocked elements

- app/operations/render_liquid.rb
This reverts commit f7b1ffd845dce37da7c6768dd71b6f08a03489bf.
> Revert "Bug fix on Sections Tab (#137)"

- .docker/development/Dockerfile
- .rubocop.yml
- Gemfile
- app/operations/render_liquid.rb
- docker-compose.yml
- spec/operations/documents/create_spec.rb
- spec/operations/render_liquid_spec.rb
- spec/rails_helper.rb
Sanitize model parameters provided to liquid template interpolation.
https://www.pivotaltracker.com/story/show/187324691
> Prevent local file read while rendering Liquid templates.
